# Podstawy głębokich sieci neuronowych
### Lab 2

In [1]:
import tensorflow as tf

2024-03-13 15:35:29.985764: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9360] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-13 15:35:29.985834: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-13 15:35:29.985854: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1537] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-13 15:35:29.992119: I tensorflow/core/platform/cpu_feature_guard.cc:183] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Zadanie 1

Napisać funkcję, która:
- Przyjmie na wejście tensor o dowolnym kształcie typu `tf.float32`.
- Utworzy maskę według warunku _x > 0_
- Na podstawie maski utworzy wektor elementów z tensora wejściowego
- Przeprowadzi mnożenie algebraiczne wynikowego wektora o siebie, ale z
transpozycją drugiego czynnika.
- Dorobi dodatkowy wymiar w osi 0 i powtórzy tensor 5 razy wzdłuż tej osi
- Zwróci wynik

Funkcję wywołać dla trzech tensorów powstałych przez użycie operacji `tf.random.uniform()` z
wartościami z zakresu _<-10,10>_ przy argumentach _shape_:
- `[3]`
- `[33, 7]`
- `[2, 32, 6]`

**Należy wykorzystać operacje**: [`tf.boolean_mask`](https://www.tensorflow.org/api_docs/python/tf/boolean_mask), [`tf.transpose`](https://www.tensorflow.org/api_docs/python/tf/transpose), [`tf.linalg.matmul`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul), [`tf.expand_dims`](https://www.tensorflow.org/api_docs/python/tf/expand_dims), [`tf.repeat`](https://www.tensorflow.org/api_docs/python/tf/repeat)

In [2]:
#def zad1_different(t):
#    assert t.dtype == tf.float32 #op1
#    op2 = t > 0
#    op3 = tf.boolean_mask(t, op2)
#    op4 = tf.linalg.matmul(op3[:, tf.newaxis], op3[:, tf.newaxis], transpose_b=True)
#    op5 = tf.repeat(op4[tf.newaxis], 5, 0)
#    return op5

# https://stackoverflow.com/questions/48100954/why-does-tf-matmula-b-transpose-b-true-work-but-not-tf-matmula-tf-transpos
# Tutaj to nie ma znaczenia, ale dowiedzialem sie, ze to daje inne rezultaty
def zad1(t):
    assert t.dtype == tf.float32 #op1
    op2 = t > 0
    op3 = tf.boolean_mask(t, op2)
    op4 = tf.linalg.matmul(op3[:, tf.newaxis], tf.transpose(op3[:, tf.newaxis]))
    op5 = tf.repeat(op4[tf.newaxis], 5, 0)
    return op5

in1 = tf.random.uniform([3], -10, 10, tf.float32)
in2 = tf.random.uniform([33, 7], -10, 10, tf.float32)
in3 = tf.random.uniform([2, 32, 6], -10, 10, tf.float32)

print(in1, "\n-->\n", zad1(in1))
print(in2, "\n-->\n", zad1(in2))
print(in3, "\n-->\n", zad1(in3))

tf.Tensor([-3.9773202  9.511524   2.9187584], shape=(3,), dtype=float32) 
-->
 tf.Tensor(
[[[90.46909  27.76184 ]
  [27.76184   8.519151]]

 [[90.46909  27.76184 ]
  [27.76184   8.519151]]

 [[90.46909  27.76184 ]
  [27.76184   8.519151]]

 [[90.46909  27.76184 ]
  [27.76184   8.519151]]

 [[90.46909  27.76184 ]
  [27.76184   8.519151]]], shape=(5, 2, 2), dtype=float32)
tf.Tensor(
[[ 6.861862    5.2372456   0.15821266 -4.4098306   0.72641563 -2.37144
   9.073942  ]
 [-9.1037655  -5.438571   -3.843639    7.9070873  -1.4471321   6.983406
  -6.1304426 ]
 [-9.033783    9.756594   -8.84253    -0.49232483  6.0573616  -0.54905415
  -1.1152096 ]
 [ 2.8883553   7.9797344   5.84332    -2.819624    3.870861    5.199132
   4.8352003 ]
 [-2.8052807   3.4334545   0.34584808 -9.175737   -8.380542    1.4555149
  -5.241883  ]
 [ 3.7110786  -6.6889215   4.4460917   7.818321    5.982623   -5.808518
   3.1963348 ]
 [ 6.6391983  -6.390369    8.213289    5.4425287   7.0722084   2.294323
   7.352215  ]
 [ 3.

2024-03-13 15:35:31.966280: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-13 15:35:31.973136: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-13 15:35:31.973182: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-13 15:35:31.974712: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-13 15:35:31.974748: I tensorflow/compile

## Zadanie 2
Napisać funkcję, która:
- Przyjmie na wejście tensor o dowolnym kształcie typu `tf.float32`.
- Sprawdzi, czy wartość minimalna w tensorze jest większa od zera. Jeśli jest, to wytnie pierwszą kolumnę tensora, a jeśli nie to drugą (za pomocą slicingu).
- Podzieli wynikowy tensor przez 8
- Zaokrągli wartości w tensorze do najbliższych liczb całkowitych
- Zmieni typ tensora na `tf.int32` i zwróci go

Funkcję wywołać dla tensorów:
- `[[5, 6], [7, 3], [4, 5]]`
- `[[-4, 5, 6], [7, 8, 9]]`

**Należy wykorzystać operacje**: [`tf.constant`](https://www.tensorflow.org/api_docs/python/tf/constant), [`tf.math.reduce_min`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min), [`tf.where`](https://www.tensorflow.org/api_docs/python/tf/where), [`tf.math.round`](https://www.tensorflow.org/api_docs/python/tf/math/round), [`tf.cast`](https://www.tensorflow.org/api_docs/python/tf/cast)

In [3]:
def zad2(t):
    assert t.dtype == tf.float32 #op1
    if (tf.math.reduce_min(t, axis=None) > 0):
        op2 = t[0]
    else:
        op2 = t[1]
    op3 = op2/8
    op4 = tf.math.round(op3)
    op5 = tf.cast(op4, tf.int32)
    return op5

in4 = tf.constant([[5, 6], [7, 3], [4, 5]], tf.float32)
in5 = tf.constant([[-4, 5, 6], [7, 8, 9]], tf.float32)

print(in4, "\n-->\n", zad2(in4))
print(in5, "\n-->\n", zad2(in5))

tf.Tensor(
[[5. 6.]
 [7. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32) 
-->
 tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor(
[[-4.  5.  6.]
 [ 7.  8.  9.]], shape=(2, 3), dtype=float32) 
-->
 tf.Tensor([1 1 1], shape=(3,), dtype=int32)


## Zadanie 3

Napisać funkcję, która:
- Przyjmie na wejście tensory o dowolnych, ale identycznych kształtach typu `tf.float32` (należy zabezpieczyć się przed odmiennymi kształtami przez asercję).
- Utworzy tensor indeksów elementów większych od 0 i mniejszych od 4 dla tensora
pierwszego.
- Na podstawie tego tensora indeksów podmieni odpowiadające wartości w tensorze
drugim na wartość 7.
- Zwróci zmodyfikowany tensor

Funkcję wywołać dla tensorów:
- `x1 = [[8, 9, 0], [2, 3, 4], [6, 1, 8]]` i `x2 = [[4, 5, 8], [23, 32, 14], [6, 1, 15]]`
- `x1 = [[8, 9], [3, 4], [6, 2]]` i `x2 = [[5, 8], [23, 14], [6, 1]]`

**Należy wykorzystać operacje**: [`tf.constant`](https://www.tensorflow.org/api_docs/python/tf/constant), [`tf.shape`](https://www.tensorflow.org/api_docs/python/tf/shape), [`tf.where`](https://www.tensorflow.org/api_docs/python/tf/where), [`tf.tensor_scatter_nd_update`](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update), [`tf.math.logical_and`](https://www.tensorflow.org/api_docs/python/tf/math/logical_and)

In [4]:
def zad3(t1, t2):
    assert t1.shape == t2.shape and t1.dtype == tf.float32 and t2.dtype == tf.float32, "Tensory sa innych ksztaltow lub zlego typu" #op1
    op2 = tf.math.logical_and(t1 > 0, t1 < 4)
    op3 = tf.tensor_scatter_nd_update(t2, tf.where(op2), tf.repeat(tf.constant([7], tf.float32), tf.shape(tf.where(op2))[0]))
    return op3

in6 = tf.constant([[8, 9, 0], [2, 3, 4], [6, 1, 8]], tf.float32)
in7 = tf.constant([[4, 5, 8], [23, 32, 14], [6, 1, 15]], tf.float32)
in8 = tf.constant([[8, 9], [3, 4], [6, 2]], tf.float32)
in9 = tf.constant([[5, 8], [23, 14], [6, 1]], tf.float32)
print(in6, "\nORAZ\n", in7, "\n-->\n", zad3(in6, in7))
print(in8, "\nORAZ\n", in9, "\n-->\n", zad3(in8, in9))

tf.Tensor(
[[8. 9. 0.]
 [2. 3. 4.]
 [6. 1. 8.]], shape=(3, 3), dtype=float32) 
ORAZ
 tf.Tensor(
[[ 4.  5.  8.]
 [23. 32. 14.]
 [ 6.  1. 15.]], shape=(3, 3), dtype=float32) 
-->
 tf.Tensor(
[[ 4.  5.  8.]
 [ 7.  7. 14.]
 [ 6.  7. 15.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[8. 9.]
 [3. 4.]
 [6. 2.]], shape=(3, 2), dtype=float32) 
ORAZ
 tf.Tensor(
[[ 5.  8.]
 [23. 14.]
 [ 6.  1.]], shape=(3, 2), dtype=float32) 
-->
 tf.Tensor(
[[ 5.  8.]
 [ 7. 14.]
 [ 6.  7.]], shape=(3, 2), dtype=float32)
